//! Modal analysis module
//! Calculates natural frequencies and mode shapes using CalculiX *FREQUENCY analysis

use serde::{Deserialize, Serialize};
use std::fs::File;
use std::io::{BufRead, BufReader};
use std::path::PathBuf;
use thiserror::Error;

use super::input_gen::{Element, Material, Model, Node};


#[derive(Error, Debug)]
pub enum ModalError {
    #[error("IO error: {0}")]
    IoError(#[from] std::io::Error),
    #[error("Parse error: {0}")]
    ParseError(String),
    #[error("Invalid mode index: {0}")]
    InvalidModeIndex(usize),
    #[error("No modal data available")]
    NoModalData,
}

/// Modal analysis configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModalAnalysisConfig {
    pub num_modes: usize,
    pub min_frequency: Option<f64>,
    pub max_frequency: Option<f64>,
    pub lumped_mass: bool,
}

impl Default for ModalAnalysisConfig {
    fn default() -> Self {
        Self {
            num_modes: 10,
            min_frequency: None,
            max_frequency: None,
            lumped_mass: false,
        }
    }
}

/// A single mode shape result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModalMode {
    pub mode_number: usize,
    pub frequency_hz: f64,
    pub eigenvalue: f64,
    pub generalized_mass: f64,
    pub node_displacements: Vec<ModeShapeNode>,
}

/// Displacement for a single node in a mode shape
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModeShapeNode {
    pub node_id: usize,
    pub dx: f64,
    pub dy: f64,
    pub dz: f64,
    pub displacement_magnitude: f64,
}

/// Complete modal analysis results
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModalResults {
    pub job_id: String,
    pub num_nodes: usize,
    pub num_elements: usize,
    pub modes: Vec<ModalMode>,
    pub warnings: Vec<String>,
    pub errors: Vec<String>,
}

impl Default for ModalResults {
    fn default() -> Self {
        Self {
            job_id: uuid::Uuid::new_v4().to_string(),
            num_nodes: 0,
            num_elements: 0,
            modes: vec![],
            warnings: vec![],
            errors: vec![],
        }
    }
}

/// Generate CalculiX input for modal analysis with *FREQUENCY step
pub fn generate_modal_inp(
    nodes: &[Node],
    elements: &[Element],
    material: &Material,
    config: &ModalAnalysisConfig,
    output_path: &str,
) -> Result<String, ModalError> {
    let _model = Model {
        nodes: nodes.to_vec(),
        elements: elements.to_vec(),
        materials: vec![material.clone()],
        steps: vec![],
        boundary_conditions: vec![],
        loads: vec![],
        contact_pairs: vec![],
    };

    // Build modal INP content
    let mut content = String::new();

    // Heading
    content.push_str("** Generated by CAELab - Modal Analysis\n");
    content.push_str("** Natural Frequency Analysis\n");
    content.push_str("\n");

    // Nodes
    content.push_str("*NODE\n");
    for node in nodes {
        content.push_str(&format!("{}, {:.6}, {:.6}, {:.6}\n", node.id, node.x, node.y, node.z));
    }
    content.push_str("\n");

    // Elements
    let mut elem_by_type: std::collections::HashMap<String, Vec<&Element>> = std::collections::HashMap::new();
    for elem in elements {
        elem_by_type
            .entry(elem.element_type.as_str().to_string())
            .or_insert_with(Vec::new)
            .push(elem);
    }

    for (etype, elems) in elem_by_type {
        content.push_str(&format!("*ELEMENT, TYPE={}\n", etype));
        for elem in elems {
            let node_list = elem.nodes.iter().map(|n| n.to_string()).collect::<Vec<_>>().join(", ");
            content.push_str(&format!("{}, {}\n", elem.id, node_list));
        }
        content.push_str("\n");
    }

    // Material
    content.push_str(&format!("*MATERIAL, NAME={}\n", material.name));
    content.push_str("*ELASTIC\n");
    content.push_str(&format!("{}, POISSON={:.6}\n", material.youngs_modulus, material.poisson_ratio));
    if material.density > 0.0 {
        content.push_str("*DENSITY\n");
        content.push_str(&format!("{:.6}\n", material.density));
    }
    content.push_str("\n");

    // Section
    content.push_str(&format!("*SOLID SECTION, ELSET=EALL, MATERIAL={}\n", material.name));
    content.push_str("\n");

    // Step - FREQUENCY analysis
    content.push_str("*STEP\n");
    content.push_str("*FREQUENCY\n");
    content.push_str(&format!("{}\n", config.num_modes));
    
    if let Some(min_f) = config.min_frequency {
        content.push_str(&format!(", {:.4}\n", min_f));
    }
    
    if let Some(max_f) = config.max_frequency {
        content.push_str(&format!(", {:.4}\n", max_f));
    }
    
    content.push_str("*NODE FILE\n");
    content.push_str("U\n");  // Output displacements
    content.push_str("*ELEMENT FILE\n");
    content.push_str("S\n");  // Output stresses (optional)
    content.push_str("*END STEP\n");

    // Write to file
    let path = PathBuf::from(output_path);
    std::fs::write(&path, &content)
        .map_err(|e| ModalError::IoError(e))?;

    tracing::info!("Modal INP generated: {} ({} modes)", output_path, config.num_modes);

    Ok(output_path.to_string())
}

/// Parse modal results from FRD file
/// FRD format for modal analysis contains:
/// - Block -1ELM: element definitions (same as static)
/// - Block -1NOD: node coordinates (same as static)
/// - Block -1DAT or -1TOST: modal displacement data
///   Mode shapes are stored as displacement U1, U2, U3 for each mode
#[allow(unused_assignments)]
pub fn parse_modal_frd(frd_path: &str) -> Result<ModalResults, ModalError> {
    let file = File::open(frd_path)
        .map_err(|e| ModalError::IoError(e))?;
    
    let lines = BufReader::new(file).lines();
    let mut results = ModalResults::default();
    
    let mut current_block: Option<String> = None;
    let mut current_mode: Option<ModalMode> = None;
    let mut mode_displacements: Vec<ModeShapeNode> = vec![];
    let mut mode_number = 0;
    let mut frequency_hz = 0.0;
    let mut eigenvalue = 0.0;
    
    let mut node_coords: std::collections::HashMap<usize, (f64, f64, f64)> = std::collections::HashMap::new();
    let mut mode_frequencies: Vec<(usize, f64, f64)> = vec![]; // (mode_num, freq_hz, eigenvalue)
    
    for (line_num, line) in lines.enumerate() {
        let line = line.map_err(|e| ModalError::ParseError(format!("Line {}: {}", line_num, e)))?;
        let line = line.trim();
        
        if line.is_empty() || line.starts_with(" 99") {
            continue;
        }
        
        // Block header
        if line.starts_with("-1") {
            // Save previous mode if any
            if let Some(mut mode) = current_mode.take() {
                mode.node_displacements = mode_displacements.clone();
                results.modes.push(mode);
                mode_displacements.clear();
            }
            
            current_block = Some(line[2..].trim().to_string());
            continue;
        }
        
        // Process block content
        if let Some(ref block) = current_block {
            if block.contains("NOD") {
                // Node coordinates
                if line.starts_with("1") {
                    let parts: Vec<&str> = line.split_whitespace().collect();
                    if parts.len() >= 4 {
                        if let (Ok(node_id), Ok(x), Ok(y), z) = (
                            parts[1].parse::<usize>(),
                            parts[2].parse::<f64>(),
                            parts[3].parse::<f64>(),
                            parts.get(4).and_then(|s| s.parse::<f64>().ok()),
                        ) {
                            let z = z.unwrap_or(0.0);
                            node_coords.insert(node_id, (x, y, z));
                            results.num_nodes += 1;
                        }
                    }
                }
            } else if block.contains("ELM") {
                // Element definitions
                if line.starts_with("1") {
                    results.num_elements += 1;
                }
            } else if block.contains("DAT") || block.contains("TOST") {
                // Result data - may contain frequency info or displacements
                if line.starts_with("1") {
                    // Dataset header - this might contain frequency info
                    let parts: Vec<&str> = line.split_whitespace().collect();
                    if parts.len() >= 3 {
                        // Check if this is a new mode
                        if let Ok(_ds_type) = parts[1].parse::<usize>() {
                            // Save previous mode
                            if let Some(mut mode) = current_mode.take() {
                                mode.node_displacements = mode_displacements.clone();
                                results.modes.push(mode);
                                mode_displacements.clear();
                            }
                            
                            mode_number = results.modes.len() + 1;
                            mode_displacements.clear();
                        }
                    }
                } else if line.starts_with("3") {
                    // Component labels line - may contain frequency info
                    // Format: "3 FREQ" or "3 0.000E+00" etc.
                    let parts: Vec<&str> = line.split_whitespace().collect();
                    for part in parts {
                        if let Ok(val) = part.parse::<f64>() {
                            if val > 0.0 && val < 100000.0 {
                                frequency_hz = val;
                                eigenvalue = (2.0 * std::f64::consts::PI * val).powi(2);
                                mode_frequencies.push((mode_number, frequency_hz, eigenvalue));
                            }
                        }
                    }
                } else if line.starts_with("2") {
                    // Nodal result data
                    let parts: Vec<&str> = line.split_whitespace().collect();
                    if parts.len() >= 2 {
                        if let Ok(node_id) = parts[1].parse::<usize>() {
                            let values: Vec<f64> = parts[2..]
                                .iter()
                                .filter_map(|s| s.parse::<f64>().ok())
                                .collect();
                            
                            let dx = values.get(0).copied().unwrap_or(0.0);
                            let dy = values.get(1).copied().unwrap_or(0.0);
                            let dz = values.get(2).copied().unwrap_or(0.0);
                            let mag = (dx * dx + dy * dy + dz * dz).sqrt();
                            
                            mode_displacements.push(ModeShapeNode {
                                node_id,
                                dx,
                                dy,
                                dz,
                                displacement_magnitude: mag,
                            });
                        }
                    }
                }
            }
        }
    }
    
    // Save last mode
    if let Some(mut mode) = current_mode.take() {
        mode.node_displacements = mode_displacements.clone();
        results.modes.push(mode);
    }
    
    // If we parsed frequencies separately, assign them
    // The FRD format for modal: each mode is a separate dataset
    // Dataset format: "1 <dataset_id>" header, then "3" with component labels,
    // then "2" lines with node displacements
    // Frequency is typically at the end of the dataset header line
    
    // Build final modes with frequency info
    // In CalculiX FRD, frequencies appear as separate lines
    // Let's do a second pass to extract frequencies
    let file2 = File::open(frd_path)
        .map_err(|e| ModalError::IoError(e))?;
    
    let lines2 = BufReader::new(file2).lines();
    let mut all_frequencies: Vec<f64> = vec![];
    let mut all_eigenvalues: Vec<f64> = vec![];
    
    for line in lines2 {
        let line = line.map_err(|e| ModalError::IoError(e))?;
        let line = line.trim();
        
        // Look for frequency values in various formats
        // "3" lines often contain frequency data
        if line.starts_with("3") {
            let parts: Vec<&str> = line.split_whitespace().collect();
            for part in parts {
                // Skip component labels
                if part == "U1" || part == "U2" || part == "U3" || part == "U" {
                    continue;
                }
                if part == "FREQ" || part == "Eigenvalue" {
                    continue;
                }
                
                // Try to parse as frequency (positive, reasonable range)
                if let Ok(val) = part.parse::<f64>() {
                    if val > 0.1 && val < 100000.0 {
                        // Could be frequency in Hz
                        // Eigenvalue = (2πf)², so f = sqrt(eigenvalue) / 2π
                        // If value is large (eigenvalue), convert
                        if val > 1000.0 {
                            // Likely eigenvalue, convert to frequency
                            let freq = val.sqrt() / (2.0 * std::f64::consts::PI);
                            if freq > 0.1 && freq < 10000.0 {
                                all_frequencies.push(freq);
                                all_eigenvalues.push(val);
                            }
                        } else {
                            // Likely frequency in Hz
                            all_frequencies.push(val);
                            all_eigenvalues.push((2.0 * std::f64::consts::PI * val).powi(2));
                        }
                    }
                }
            }
        }
    }
    
    // Assign frequencies to modes
    for (i, mode) in results.modes.iter_mut().enumerate() {
        mode.mode_number = i + 1;
        if i < all_frequencies.len() {
            mode.frequency_hz = all_frequencies[i];
            mode.eigenvalue = all_eigenvalues[i];
        } else {
            // Estimate from displacement magnitude pattern
            // This is a fallback - real implementation needs proper FRD parsing
            mode.frequency_hz = 0.0;
            mode.eigenvalue = 0.0;
        }
        mode.generalized_mass = 1.0; // Calculated by solver
    }
    
    tracing::info!("Parsed {} modal modes from {}", results.modes.len(), frd_path);
    
    Ok(results)
}

/// Generate a sample modal result for testing/development
#[allow(dead_code)]
pub fn generate_sample_modal_results(num_modes: usize) -> ModalResults {
    let mut results = ModalResults::default();
    results.num_nodes = 100;
    results.num_elements = 50;
    
    for i in 0..num_modes {
        // Generate plausible frequencies (first few modes of a typical structure)
        let base_freq = 50.0 + (i as f64) * 30.0; // Hz
        let eigenvalue = (2.0 * std::f64::consts::PI * base_freq).powi(2);
        
        let mode = ModalMode {
            mode_number: i + 1,
            frequency_hz: base_freq,
            eigenvalue,
            generalized_mass: 1.0,
            node_displacements: vec![],
        };
        
        results.modes.push(mode);
    }
    
    results
}

/// Get summary of modal results
pub fn get_modal_summary(results: &ModalResults) -> String {
    let mut summary = format!("Modal Analysis Results:\n");
    summary.push_str(&format!("  Modes found: {}\n", results.modes.len()));
    summary.push_str(&format!("  Nodes analyzed: {}\n", results.num_nodes));
    summary.push_str(&format!("  Elements analyzed: {}\n", results.num_elements));
    summary.push_str("\n  Natural Frequencies:\n");
    
    for mode in &results.modes {
        summary.push_str(&format!(
            "    Mode {:2}: {:.2} Hz (λ={:.2})\n",
            mode.mode_number, mode.frequency_hz, mode.eigenvalue
        ));
    }
    
    summary
}

// ============================================================================
// Tauri Commands
// ============================================================================

use tauri::command;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModalModeInfo {
    pub mode_number: usize,
    pub frequency_hz: f64,
    pub eigenvalue: f64,
}

/// Generate modal analysis input file
#[command]
pub fn generate_modal_analysis_inp(
    nodes: Vec<Node>,
    elements: Vec<Element>,
    material: Material,
    num_modes: usize,
    output_path: String,
) -> Result<String, String> {
    let config = ModalAnalysisConfig {
        num_modes,
        ..Default::default()
    };
    
    generate_modal_inp(&nodes, &elements, &material, &config, &output_path)
        .map_err(|e| e.to_string())
}

/// Run modal analysis solver
#[command]
pub fn run_modal_solver(
    input_file: String,
    working_dir: String,
    num_threads: Option<usize>,
) -> Result<super::solver::SolverResult, String> {
    use super::solver::{CalculiXSolver, SolverConfig};
    
    let config = SolverConfig {
        executable_path: "ccx".to_string(),
        num_threads: num_threads.unwrap_or(4),
        memory_limit_mb: None,
    };
    
    let calc_solver = CalculiXSolver::new(config);
    let input_path = PathBuf::from(&input_file);
    let work_dir = PathBuf::from(&working_dir);
    
    calc_solver.solve(&input_path, &work_dir)
        .map_err(|e| e.to_string())
}

/// Parse modal results from FRD file
#[command]
pub fn parse_modal_results(frd_file: String) -> Result<ModalResults, String> {
    parse_modal_frd(&frd_file)
        .map_err(|e| e.to_string())
}

/// Get list of available modes from results
#[command]
pub fn get_modal_mode_list(frd_file: String) -> Result<Vec<ModalModeInfo>, String> {
    let results = parse_modal_frd(&frd_file)
        .map_err(|e| e.to_string())?;
    
    let modes: Vec<ModalModeInfo> = results.modes.iter()
        .map(|m| ModalModeInfo {
            mode_number: m.mode_number,
            frequency_hz: m.frequency_hz,
            eigenvalue: m.eigenvalue,
        })
        .collect();
    
    Ok(modes)
}

/// Get specific mode shape from results
#[command]
pub fn get_mode_shape(frd_file: String, mode_number: usize) -> Result<ModalMode, String> {
    let results = parse_modal_frd(&frd_file)
        .map_err(|e| e.to_string())?;
    
    results.modes.iter()
        .find(|m| m.mode_number == mode_number)
        .cloned()
        .ok_or_else(|| format!("Mode {} not found", mode_number))
}

/// Export mode shape to displacement result format
#[command]
pub fn export_mode_shape_as_displacement(
    nodes: Vec<Node>,
    frd_file: String,
    mode_number: usize,
    scale: f64,
) -> Result<Vec<NodeDisplacement>, String> {
    let results = parse_modal_frd(&frd_file)
        .map_err(|e| e.to_string())?;
    
    let mode = results.modes.iter()
        .find(|m| m.mode_number == mode_number)
        .ok_or_else(|| format!("Mode {} not found", mode_number))?;
    
    let displacements: Vec<NodeDisplacement> = nodes.iter()
        .map(|n| {
            let shape = mode.node_displacements.iter()
                .find(|s| s.node_id == n.id);
            
            match shape {
                Some(s) => NodeDisplacement {
                    node_id: n.id,
                    x: n.x,
                    y: n.y,
                    z: n.z,
                    ux: s.dx * scale,
                    uy: s.dy * scale,
                    uz: s.dz * scale,
                    magnitude: s.displacement_magnitude * scale,
                },
                None => NodeDisplacement {
                    node_id: n.id,
                    x: n.x,
                    y: n.y,
                    z: n.z,
                    ux: 0.0,
                    uy: 0.0,
                    uz: 0.0,
                    magnitude: 0.0,
                },
            }
        })
        .collect();
    
    Ok(displacements)
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NodeDisplacement {
    pub node_id: usize,
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub ux: f64,
    pub uy: f64,
    pub uz: f64,
    pub magnitude: f64,
}

/// Get mode animation keyframes for smooth animation
#[command]
pub fn get_mode_animation_frames(
    nodes: Vec<Node>,
    frd_file: String,
    mode_number: usize,
    num_frames: usize,
    amplitude: f64,
) -> Result<Vec<AnimationFrame>, String> {
    let results = parse_modal_frd(&frd_file)
        .map_err(|e| e.to_string())?;
    
    let mode = results.modes.iter()
        .find(|m| m.mode_number == mode_number)
        .ok_or_else(|| format!("Mode {} not found", mode_number))?;
    
    let mut frames = vec![];
    
    for frame_idx in 0..num_frames {
        let phase = (frame_idx as f64 / num_frames as f64) * 2.0 * std::f64::consts::PI;
        let sin_val = phase.sin();
        
        let displacements: Vec<NodeDisplacement> = nodes.iter()
            .map(|n| {
                let shape = mode.node_displacements.iter()
                    .find(|s| s.node_id == n.id);
                
                match shape {
                    Some(s) => NodeDisplacement {
                        node_id: n.id,
                        x: n.x,
                        y: n.y,
                        z: n.z,
                        ux: s.dx * amplitude * sin_val,
                        uy: s.dy * amplitude * sin_val,
                        uz: s.dz * amplitude * sin_val,
                        magnitude: s.displacement_magnitude * amplitude * sin_val.abs(),
                    },
                    None => NodeDisplacement {
                        node_id: n.id,
                        x: n.x,
                        y: n.y,
                        z: n.z,
                        ux: 0.0,
                        uy: 0.0,
                        uz: 0.0,
                        magnitude: 0.0,
                    },
                }
            })
            .collect();
        
        frames.push(AnimationFrame {
            frame_index: frame_idx,
            phase,
            displacements,
        });
    }
    
    Ok(frames)
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnimationFrame {
    pub frame_index: usize,
    pub phase: f64,
    pub displacements: Vec<NodeDisplacement>,
}